### ISSUE TITLE
Redis error in prod

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-auth-service#37]
Using the prod setup[1], I get this error in a fixed interval:

```
[ioredis] Unhandled error event: Error: connect ETIMEDOUT
auth_1              |     at Socket.<anonymous> (/app/node_modules/ioredis/built/redis/index.js:285:37)
auth_1              |     at Object.onceWrapper (events.js:421:28)
auth_1              |     at Socket.emit (events.js:315:20)
auth_1              |     at Socket._onTimeout (net.js:481:8)
auth_1              |     at listOnTimeout (internal/timers.js:549:17)
auth_1              |     at processTimers (internal/timers.js:492:7)
```

[1] Nearly done: https://github.com/OpenSlides/OpenSlides/pull/5621 If you have questions, ask me!

**Comment by GabrielInTheWorld** [comment]
Is this still happen?
