### ISSUE TITLE
TypeError after invalid datastore response

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-auth-service#73]
Traceback:
```
Apr  9 14:07:56 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]: #033[97m[09.04.2021 -- 12:07:56]: http://auth:9004: POST -- /internal/auth/authenticate #033[0m
Apr  9 14:07:56 docker-dev1 docker/os4_datastore-reader.1.r80q20ehfafn5nxrc98yolw03/5915380e9f95[10357]: [2021-04-09 12:07:56 +0000] [12] [INFO] FILTER-request: {'collection': 'user', 'filter': {'field': 'id', 'value': 1, 'operator': '='}, 'mapped_fields': ['username', 'password', 'id', 'is_active']}
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]: #033[97m[09.04.2021 -- 12:17:58]: http://auth:9004: POST -- /internal/auth/authenticate #033[0m
Apr  9 14:17:58 docker-dev1 docker/os4_datastore-reader.1.r80q20ehfafn5nxrc98yolw03/5915380e9f95[10357]: [2021-04-09 12:17:58 +0000] [11] [INFO] FILTER-request: {'collection': 'user', 'filter': {'field': 'id', 'value': 1, 'operator': '='}, 'mapped_fields': ['username', 'password', 'id', 'is_active']}
Apr  9 14:17:58 docker-dev1 docker/os4_datastore-reader.1.r80q20ehfafn5nxrc98yolw03/5915380e9f95[10357]: [2021-04-09 12:17:58 +0000] [11] [ERROR] Connection handler error: Database connection error (type) <member 'pgcode' of 'psycopg2.Error' objects>: <member 'pgerror' of 'psycopg2.Error' objects>
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]: (node:33) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]:     at TicketService.decode (/app/build/src/api/services/ticket-service.js:58:35)
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]:     at TicketService.<anonymous> (/app/build/src/api/services/ticket-service.js:154:42)
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]:     at Generator.next (<anonymous>)
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]:     at fulfilled (/app/node_modules/tslib/tslib.js:112:62)
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]: (Use `node --trace-warnings ...` to show where the warning was created)
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]: (node:33) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Apr  9 14:17:58 docker-dev1 docker/os4_auth.1.zvh80r3n62bl9wx3zvh9aj7sx/4060172c20cb[10357]: (node:33) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It should be caught somewhere if the datastore sends an error.

**Comment by GabrielInTheWorld** [comment]
Can you provide steps to reproduce, please?

**Comment by jsangmeister** [comment]
> Can you provide steps to reproduce, please?

Unfortunately not, I discovered this in the dump of log messages while debugging the productive setup. But the code positions are given - maybe just check these, try to trace back the error source and ensure that invalid data is also handled without error. I suspect this could also be reproduced by any 500 response from the datastore - maybe mock the datastore response in a test and check if thats the case.
